
version: 0.3.{build}
max_jobs: 1
configuration: Release
platform: Any CPU
image: Visual Studio 2017

before_build:
  - nuget restore
build:
  project: 6502.sln
  parallel: true
  verbosity: minimal
  